In [2]:
import matplotlib.pyplot as plt
import numpy as np
import ipywidgets as widgets
from ipywidgets import interact, interactive, fixed, interact_manual

###ex1
matrice=np.array([[1,2,3],
        [3,2,11],
        [2,1,5]])
m,n=np.where(matrice==3)
result = zip(m,n)
resultSet = set(result)
print(resultSet)


{(1, 0), (0, 2)}


In [3]:
###ex2
print(np.prod(matrice,axis=1))

[ 6 66 10]


In [4]:
###ex3
matrice2=np.array([[5,2,3],
        [3,2,2],
        [2,1,5]])
np.all(matrice2>=matrice)

False

In [5]:
###ex4
m,n=np.where(matrice2==matrice2.max()) 
result = zip(m,n)
resultSet = set(result)
print(resultSet)
print(matrice2==matrice2.max()) 

{(0, 0), (2, 2)}
[[ True False False]
 [False False False]
 [False False  True]]


In [6]:
###ex5
a = np.array([230, 10, 284, 39, 76])

while(a[a<100].any()):
    a[a<100]*=2
    
print(a[np.logical_and(a>150,a<200)])

[160 156 152]


In [7]:
###ex6
a = np.array([3, 7, 9, 13, -10, 200, 3])
b = np.array([4, 5, -9, 100, 300, 230, 1])

def pair_max(a,b):
    '''
    Functia returneaza maximul dintre 2 vectori de aceeasi lungime
    param a: primul vector
    :param b: al doile vector
    '''
    return np.maximum(a,b)

pair_max(a,b)

array([  4,   7,   9, 100, 300, 230,   3])

In [9]:
%%timeit
tab = np.array([[1.0, 2.3, np.nan, 4], [10, np.nan, np.nan, 0]])
def sum1(tab):
    '''Functia afiseaza suma tuturor elementelor dintr-un vector dat (elementele NaN vor fi inlocuite cu 0)
    foloseste functia np.isnan()
    '''
    copie=np.copy(tab)
    copie[np.isnan(tab)] = 0.0
    print(np.sum(copie))
    
sum1(tab)

17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3


17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3


17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3


17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3


17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
17.3
632 µs ± 4

In [10]:
%%timeit
tab = np.array([[1.0, 2.3, np.nan, 4], [10, np.nan, np.nan, 0]])
def sum2(tab):
    '''Functia afiseaza suma tuturor elementelor dintr-un vector dat (elementele NaN nu vor fi luate in considerare)
    foloseste functia np.nansum()
    '''
    np.nansum(tab)
sum2(tab)

39.4 µs ± 9.57 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [11]:
%%timeit
tab = np.array([[1.0, 2.3, np.nan, 4], [10, np.nan, np.nan, 0]])
def sum3(tab):
    '''Functia afiseaza suma tuturor elementelor dintr-un vector dat (elementele NaN nu vor fi luate in considerare)
    foloseste indiciere booleana
    '''
    np.sum(tab[~np.isnan(tab)])
sum3(tab)

24.1 µs ± 3.33 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [12]:
###ex8
def citeste_din_fisier(nume_fisier):
    '''Functia returneaza setul de date care se afla la numele fisierlui dat ca parametru
    param nume_fisier: Numele fisierului de unde se citesc datele
    '''
    date=np.genfromtxt(nume_fisier, delimiter=',')
    return date

def pune_random_Nan(x):
    '''Pune valori nan random intr-o matrice cu 150 de linii si 4 coloane, data ca parametru
    Returneaza apoi matricea
    '''
    valori_randomX = np.random.randint(150, size=10)
    valori_randomY = np.random.randint(4, size=10)
    z = zip(valori_randomX, valori_randomY)
    for i, j in zip(valori_randomX, valori_randomY):
        x[i, j] = np.nan
    return x

def afla_pozitiile_NaN(x):
    '''Returneaza 2 vectori care contin indicii liniilor si coloanelor pe care se afla valori Nan
    '''
    p1, p2 = np.where(np.isnan(x))
    return p1, p2 
    
date = citeste_din_fisier("iris.txt")
date = date[:, 0:-1]
date = pune_random_Nan(date)
p1, p2 = afla_pozitiile_NaN(date)
p = zip(p1, p2)
poz = set(p)
print(poz)

{(123, 0), (72, 3), (1, 3), (141, 2), (62, 2), (28, 1), (5, 1), (46, 2), (0, 2), (45, 0)}


In [13]:
###ex9
def pe_langa_interval(matrice,stanga,dreapta):
    '''Determina pe ce pozitii se afla valorile dintr-o matrice care sunt in afara unui interval inchis dat
    param matrice: matricea pe care se vor cauta pozitiile
    param stanga: capatul inferior al intervalului
    param dreapta: capatul exterior al intervalului
    '''
    matrice=np.logical_or(matrice<stanga,matrice>dreapta)
    m,n=np.where(matrice==True)
    result = zip(m,n)
    resultSet = set(result)
    print(resultSet)
    print(matrice)

pe_langa_interval(matrice,3,5) 

{(0, 1), (1, 2), (0, 0), (2, 1), (2, 0), (1, 1)}
[[ True  True False]
 [False  True  True]
 [ True  True False]]


In [14]:
###ex10
#trebuie returnate si pozitiile lor din vectorul initial
import pandas as pd
def maxK(a,k):
    '''Returneaza pozitiile celor mai mari k valori dintr-un array, impreuna cu valorile lor
    param a: array-ul dat
    param k: nr de valori
    '''
    vector = pd.Series(a)
    
    return vector.nlargest(k)

print(maxK(a,3))

5    200
3     13
2      9
dtype: int32
